### ISSUE TITLE
predict() generates different predictions if called with multiple points at once versus called with each point individually

### ISSUE THREAD

**Issue by JenniferSLyon** [tkonopka/umap#9]
If I call predict() with a data.frame of points, and then call predict() with each point separately I get different results, some times substantially different. For my application I need to get the same result for the same input data. Unfortunately, the obvious solution of running each point through separately is about 100x slower. I'm not sure if this is a bug or just a characteristic of the algorithm.

Here is an example taken from the vignette:
iris.data = iris[, grep("Sepal|Petal", colnames(iris))]
iris.labels = iris[, "Species"]
iris.umap = umap(iris.data)

set.seed(19)
iris.wnoise = iris.data + matrix(rnorm(150*40, 0, 0.1), ncol=4)
colnames(iris.wnoise) = colnames(iris.data)
iris.wnoise.umap = predict(iris.umap, iris.wnoise)

iris.wnoise.umap.1 = t(apply(iris.wnoise, 1, function(x) {
   x <- t(matrix(x))
   predict(iris.umap, x)
}))

head(cbind(iris.wnoise.umap, iris.wnoise.umap.1))
      [,1]        [,2]     [,3]        [,4]
1 16.28199 -0.70549906 15.92311 -0.47269093
2 14.69319 -2.22523708 14.16301 -2.27630185
3 14.78369 -3.54772123 15.00407 -3.04123797
4 14.36916 -2.48618578 14.13746 -2.43722985
5 16.04017 -0.44320957 16.37358 -0.64862115
6 15.90486  0.05976971 16.48200  0.09985856

**Comment by tkonopka** [comment]
Thanks. An interesting effect and I think it is reasonable to look for consistency in predictions performed one-at-a-time and in batch. 

On consistency - some random numbers are used in the optimization of the coordinates and these random numbers turn out to be used in a slightly different way if you run `predict` on single items and on many at once. This could be resolved and I will look into it. Interestingly, the same effect happens in the `naive` implementation and when interfacing with `umap-learn` (0.3.9). Would you like to raise this on the [python umap repo](https://github.com/lmcinnes/umap/issues) as well?

On performance - the slowness you are noticing is probably due to how nearest neighbors are evaluated in the `naive` implementation. This is a limitation of the current `naive` implementation and not a fundamental drawback. (I suspect that `umap-learn` will have much better characteristics there.) This issue could be addressed and I think it would be worthwhile but would require more substantial changes.

**Comment by JenniferSLyon** [comment]
Thank you for the explanation of why the results differ, and I hope you are able to get the results of predict() to be consistent.

Just to be clear, my comment about timing were just to note why I didn't do the obvious thing and just always predict one at a time. Here are the timings for doing the entire data.frame and doing it one at a time. The difference makes it impractical to consider doing predictions one at a time. That is all I meant. The speed of doing the entire data.frame at once is very reasonable.
Again using the iris example:

## All at once
system.time(predict(iris.umap, iris.wnoise))
   user  system elapsed
  0.380   0.000   0.381

## One at a time
system.time(t(apply(iris.wnoise, 1, function(x) {
   x <- t(matrix(x))
   predict(iris.umap, x)
})))

   user  system elapsed
 23.543   0.007  23.550

Finally, I am not a Python person. I am happy to leave a note on the python umap repo, pointing to this discussion, which they may find interesting.

**Comment by JenniferSLyon** [comment]
Thank you for the explanation of why the results differ, and I hope you are able to get the results of predict() to be consistent.

Just to be clear, my comment about timing were just to note why I didn't do the obvious thing and just always predict one at a time. Here are the timings for doing the entire data.frame and doing it one at a time. The difference makes it impractical to consider doing predictions one at a time. That is all I meant. The speed of doing the entire data.frame at once is very reasonable.
Again using the iris example:

## All at once
system.time(predict(iris.umap, iris.wnoise))
   user  system elapsed
  0.380   0.000   0.381

## One at a time
system.time(t(apply(iris.wnoise, 1, function(x) {
   x <- t(matrix(x))
   predict(iris.umap, x)
})))

   user  system elapsed
 23.543   0.007  23.550

Finally, I am not a Python person. I am happy to leave a note on the python umap repo, pointing to this discussion, which they may find interesting.

**Comment by JenniferSLyon** [comment]
It actually looks like Issue 158 "Are umap transformations non-deterministic?" is discussing this issue over in the Python implementation. https://github.com/lmcinnes/umap/issues/158

**Comment by tkonopka** [comment]
Quick update: I'm experimenting with a quasi-stable predict in branch "stable_predict". It seems to work but still want to look into performance and an update to the vignette.

**Comment by tkonopka** [comment]
This should now be resolved (version 0.2.3) and predictions on small batches should give the same outcomes as predictions on individual items. There are some caveats, though, see the vignette. In particular, discrepancies remain between predictions on small and large batches. These appear because small batches (<1000 items) use exact nearest neighbors and large batches use approximate neighbors. Perhaps this could also be resolved but it would require major changes in the codebase.

**Comment by JenniferSLyon** [comment]
tested with version 0.2.3 in my application and prediction results are now deterministic. Thank you.
